import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const { prompt, aiContext } = await request.json();

    if (!prompt?.trim()) {
      return NextResponse.json(
        { error: 'Prompt is required' },
        { status: 400 }
      );
    }

    // Use Hugging Face's text generation model
    const response = await fetch('https://router.huggingface.co/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.HUGGINGFACE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        messages: [
          {
            role: "user",
            content: `${
              aiContext ? "Generate a recipe following the following user's preferences" + aiContext +
              "\n The generate recipe should be in the following JSON format:"
              :"Generate recipe in the following JSON format:"
            }
            {
            "Title": "Recipe Title",
            "Description": "A brief description of the recipe",
            "Ingredients": "- ingredient 1\n- ingredient 2\n- ingredient 3",
            "Instructions": "1. Step one\n2. Step two\n3. Step three"
            }
            The user's recipe request: ${prompt}`}
          ], 
          model: "deepseek-ai/DeepSeek-V3.2:novita",
      }),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      console.error('Hugging Face API error:', response.status, errorData);
      
      if (response.status === 503) {
        return NextResponse.json(
          { error: 'AI model is loading, please try again in a moment' },
          { status: 503 }
        );
      }
      
      return NextResponse.json(
        { error: 'Failed to generate recipe' },
        { status: 500 }
      );
    }

    const data = await response.json();
    console.log('Hugging Face API response data:', data);
    console.log('Full response:', data?.choices?.[0]?.message);
    
    const recipe: {
      title?: string;
      description?: string;
      ingredients?: string;
      instructions?: string;
    } = {};      

    let jsonData = data?.choices?.[0]?.message?.content;

    if (jsonData) {
      // Strip everything outside the outermost curly brackets
      const firstBracket = jsonData.indexOf('{');
      const lastBracket = jsonData.lastIndexOf('}');
      
      if (firstBracket !== -1 && lastBracket !== -1 && lastBracket > firstBracket) {
        jsonData = jsonData.slice(firstBracket, lastBracket + 1);
      }
      if (jsonData.length = 0) {
        return NextResponse.json(
          { error: 'Recipe failed to generate. Please try again.' },
          { status: 400 }
        );
      }

      try {
        const parsedRecipe = JSON.parse(jsonData);
        recipe.title = parsedRecipe.Title;
        recipe.description = parsedRecipe.Description;
        recipe.ingredients = parsedRecipe.Ingredients;
        recipe.instructions = parsedRecipe.Instructions;
      } catch (parseError) {
        console.error('Failed to parse JSON from AI response:', parseError);
        console.log('Raw jsonData:', jsonData);
        
        return NextResponse.json(
          { error: 'Recipe failed to generate. Please try again.' },
          { status: 400 }
        );
      }
    } else {
      return NextResponse.json(
        { error: 'No content generated by AI' },
        { status: 500 }
      );
    }
    
    return NextResponse.json({ 
      content: recipe.description,
      recipe: recipe 
    });
  } catch (error) {
    console.error('Error in AI generation API:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
